module.exports = {
  'rules': {
    // http://eslint.org/docs/rules/comma-dangle
    'comma-dangle': 0,
    // http://eslint.org/docs/rules/no-cond-assign
    'no-cond-assign': 0,
    // http://eslint.org/docs/rules/no-console
    'no-console': 0,
    // http://eslint.org/docs/rules/no-constant-condition
    'no-constant-condition': 0,
    // http://eslint.org/docs/rules/no-control-regex
    'no-control-regex': 0,
    // http://eslint.org/docs/rules/no-debugger
    'no-debugger': 0,
    // http://eslint.org/docs/rules/no-dupe-args
    'no-dupe-args': 0,
    // http://eslint.org/docs/rules/no-dupe-keys
    'no-dupe-keys': 0,
    // http://eslint.org/docs/rules/no-duplicate-case
    'no-duplicate-case': 0,
    // http://eslint.org/docs/rules/no-empty
    'no-empty': 0,
    // http://eslint.org/docs/rules/no-empty-character-class
    'no-empty-character-class': 0,
    // http://eslint.org/docs/rules/no-ex-assign
    'no-ex-assign': 0,
    // http://eslint.org/docs/rules/no-extra-boolean-cast
    'no-extra-boolean-cast': 0,
    // http://eslint.org/docs/rules/no-extra-parens
    'no-extra-parens': 0,
    // http://eslint.org/docs/rules/no-extra-semi
    'no-extra-semi': 0,
    // http://eslint.org/docs/rules/no-func-assign
    'no-func-assign': 0,
    // http://eslint.org/docs/rules/no-inner-declarations
    'no-inner-declarations': 0,
    // http://eslint.org/docs/rules/no-invalid-regexp
    'no-invalid-regexp': 0,
    // http://eslint.org/docs/rules/no-irregular-whitespace
    'no-irregular-whitespace': 0,
    // http://eslint.org/docs/rules/no-negated-in-lhs
    'no-negated-in-lhs': 0,
    // http://eslint.org/docs/rules/no-obj-calls
    'no-obj-calls': 0,
    // http://eslint.org/docs/rules/no-regex-spaces
    'no-regex-spaces': 0,
    // http://eslint.org/docs/rules/no-sparse-arrays
    'no-sparse-arrays': 0,
    // http://eslint.org/docs/rules/no-unexpected-multiline
    'no-unexpected-multiline': 0,
    // http://eslint.org/docs/rules/no-unreachable
    'no-unreachable': 0,
    // http://eslint.org/docs/rules/use-isnan
    'use-isnan': 0,
    // http://eslint.org/docs/rules/valid-jsdoc
    'valid-jsdoc': 0,
    // http://eslint.org/docs/rules/valid-typeof
    'valid-typeof': 0,
  },
};
