module.exports = {
  'parserOptions': {
    'ecmaVersion': 6,
  },
  'env': {
    'es6': true,
  },
  'rules': {
    // http://eslint.org/docs/rules/arrow-body-style
    'arrow-body-style': 0,
    // http://eslint.org/docs/rules/arrow-parens
    'arrow-parens': 0,
    // http://eslint.org/docs/rules/arrow-spacing
    'arrow-spacing': 0,
    // http://eslint.org/docs/rules/constructor-super
    'constructor-super': 0,
    // http://eslint.org/docs/rules/generator-star-spacing
    'generator-star-spacing': 0,
    // http://eslint.org/docs/rules/no-class-assign
    'no-class-assign': 0,
    // http://eslint.org/docs/rules/no-confusing-arrow
    'no-confusing-arrow': 0,
    // http://eslint.org/docs/rules/no-const-assign
    'no-const-assign': 0,
    // http://eslint.org/docs/rules/no-dupe-class-members
    'no-dupe-class-members': 0,
    // http://eslint.org/docs/rules/no-duplicate-imports
    'no-duplicate-imports': 0,
    // http://eslint.org/docs/rules/no-new-symbol
    'no-new-symbol': 0,
    // http://eslint.org/docs/rules/no-restricted-imports
    'no-restricted-imports': 0,
    // http://eslint.org/docs/rules/no-this-before-super
    'no-this-before-super': 0,
    // http://eslint.org/docs/rules/no-useless-computed-key
    'no-useless-computed-key': 0,
    // http://eslint.org/docs/rules/no-useless-constructor
    'no-useless-constructor': 0,
    // http://eslint.org/docs/rules/no-var
    'no-var': 0,
    // http://eslint.org/docs/rules/object-shorthand
    'object-shorthand': 0,
    // http://eslint.org/docs/rules/prefer-arrow-callback
    'prefer-arrow-callback': 0,
    // http://eslint.org/docs/rules/prefer-const
    'prefer-const': 0,
    // http://eslint.org/docs/rules/prefer-reflect
    'prefer-reflect': 0,
    // http://eslint.org/docs/rules/prefer-rest-params
    'prefer-rest-params': 0,
    // http://eslint.org/docs/rules/prefer-spread
    'prefer-spread': 0,
    // http://eslint.org/docs/rules/prefer-template
    'prefer-template': 0,
    // http://eslint.org/docs/rules/require-yield
    'require-yield': 0,
    // http://eslint.org/docs/rules/template-curly-spacing
    'template-curly-spacing': 0,
    // http://eslint.org/docs/rules/yield-star-spacing
    'yield-star-spacing': 0,
  },
}
