module.exports = {
  'rules': {
    // http://eslint.org/docs/rules/array-bracket-spacing
    'array-bracket-spacing': 0,
    // http://eslint.org/docs/rules/block-spacing
    'block-spacing': 0,
    // http://eslint.org/docs/rules/brace-style
    'brace-style': 0,
    // http://eslint.org/docs/rules/camelcase
    'camelcase': 0,
    // http://eslint.org/docs/rules/comma-spacing
    'comma-spacing': 0,
    // http://eslint.org/docs/rules/comma-style
    'comma-style': 0,
    // http://eslint.org/docs/rules/computed-property-spacing
    'computed-property-spacing': 0,
    // http://eslint.org/docs/rules/consistent-this
    'consistent-this': 0,
    // http://eslint.org/docs/rules/eol-last
    'eol-last': 0,
    // http://eslint.org/docs/rules/func-names
    'func-names': 0,
    // http://eslint.org/docs/rules/func-style
    'func-style': 0,
    // http://eslint.org/docs/rules/id-blacklist
    'id-blacklist': 0,
    // http://eslint.org/docs/rules/id-length
    'id-length': 0,
    // http://eslint.org/docs/rules/id-match
    'id-match': 0,
    // http://eslint.org/docs/rules/indent
    'indent': 0,
    // http://eslint.org/docs/rules/jsx-quotes
    'jsx-quotes': 0,
    // http://eslint.org/docs/rules/key-spacing
    'key-spacing': 0,
    // http://eslint.org/docs/rules/keyword-spacing
    'keyword-spacing': 0,
    // http://eslint.org/docs/rules/linebreak-style
    'linebreak-style': 0,
    // http://eslint.org/docs/rules/lines-around-comment
    'lines-around-comment': 0,
    // http://eslint.org/docs/rules/max-depth
    'max-depth': 0,
    // http://eslint.org/docs/rules/max-len
    'max-len': 0,
    // http://eslint.org/docs/rules/max-nested-callbacks
    'max-nested-callbacks': 0,
    // http://eslint.org/docs/rules/max-params
    'max-params': 0,
    // http://eslint.org/docs/rules/max-statements
    'max-statements': 0,
    // http://eslint.org/docs/rules/new-cap
    'new-cap': 0,
    // http://eslint.org/docs/rules/new-parens
    'new-parens': 0,
    // http://eslint.org/docs/rules/newline-after-var
    'newline-after-var': 0,
    // http://eslint.org/docs/rules/newline-before-return
    'newline-before-return': 0,
    // http://eslint.org/docs/rules/newline-per-chained-call
    'newline-per-chained-call': 0,
    // http://eslint.org/docs/rules/no-array-constructor
    'no-array-constructor': 0,
    // http://eslint.org/docs/rules/no-bitwise
    'no-bitwise': 0,
    // http://eslint.org/docs/rules/no-continue
    'no-continue': 0,
    // http://eslint.org/docs/rules/no-inline-comments
    'no-inline-comments': 0,
    // http://eslint.org/docs/rules/no-lonely-if
    'no-lonely-if': 0,
    // http://eslint.org/docs/rules/no-mixed-spaces-and-tabs
    'no-mixed-spaces-and-tabs': 0,
    // http://eslint.org/docs/rules/no-multiple-empty-lines
    'no-multiple-empty-lines': 0,
    // http://eslint.org/docs/rules/no-negated-condition
    'no-negated-condition': 0,
    // http://eslint.org/docs/rules/no-nested-ternary
    'no-nested-ternary': 0,
    // http://eslint.org/docs/rules/no-new-object
    'no-new-object': 0,
    // http://eslint.org/docs/rules/no-plusplus
    'no-plusplus': 0,
    // http://eslint.org/docs/rules/no-restricted-syntax
    'no-restricted-syntax': 0,
    // http://eslint.org/docs/rules/no-spaced-func
    'no-spaced-func': 0,
    // http://eslint.org/docs/rules/no-ternary
    'no-ternary': 0,
    // http://eslint.org/docs/rules/no-trailing-spaces
    'no-trailing-spaces': 0,
    // http://eslint.org/docs/rules/no-underscore-dangle
    'no-underscore-dangle': 0,
    // http://eslint.org/docs/rules/no-unneeded-ternary
    'no-unneeded-ternary': 0,
    // http://eslint.org/docs/rules/no-whitespace-before-property
    'no-whitespace-before-property': 0,
    // http://eslint.org/docs/rules/object-curly-spacing
    'object-curly-spacing': 0,
    // http://eslint.org/docs/rules/one-var
    'one-var': 0,
    // http://eslint.org/docs/rules/one-var-declaration-per-line
    'one-var-declaration-per-line': 0,
    // http://eslint.org/docs/rules/operator-assignment
    'operator-assignment': 0,
    // http://eslint.org/docs/rules/operator-linebreak
    'operator-linebreak': 0,
    // http://eslint.org/docs/rules/padded-blocks
    'padded-blocks': 0,
    // http://eslint.org/docs/rules/quote-props
    'quote-props': 0,
    // http://eslint.org/docs/rules/quotes
    'quotes': 0,
    // http://eslint.org/docs/rules/require-jsdoc
    'require-jsdoc': 0,
    // http://eslint.org/docs/rules/semi
    'semi': 0,
    // http://eslint.org/docs/rules/semi-spacing
    'semi-spacing': 0,
    // http://eslint.org/docs/rules/sort-imports
    'sort-imports': 0,
    // http://eslint.org/docs/rules/sort-vars
    'sort-vars': 0,
    // http://eslint.org/docs/rules/space-before-blocks
    'space-before-blocks': 0,
    // http://eslint.org/docs/rules/space-before-function-paren
    'space-before-function-paren': 0,
    // http://eslint.org/docs/rules/space-in-parens
    'space-in-parens': 0,
    // http://eslint.org/docs/rules/space-infix-ops
    'space-infix-ops': 0,
    // http://eslint.org/docs/rules/space-unary-ops
    'space-unary-ops': 0,
    // http://eslint.org/docs/rules/spaced-comment
    'spaced-comment': 0,
    // http://eslint.org/docs/rules/wrap-regex
    'wrap-regex': 0,
  },
}
